# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('azapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_image',
            field=models.ImageField(null=True, upload_to='activity/'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='partner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Partners'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Parents'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner_image',
            field=models.ImageField(null=True, upload_to='partner/'),
        ),
    ]
