# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_cont', models.CharField(max_length=120)),
                ('commented_act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Activities')),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Parents')),
            ],
        ),
    ]
