# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0002_auto_20191118_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='partner_image',
            new_name='partner_name',
        ),
    ]
