# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0002_auto_20191120_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='residence',
            new_name='location',
        ),
        migrations.AddField(
            model_name='parents',
            name='image',
            field=models.ImageField(null=True, upload_to='parent/'),
        ),
    ]
