# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0002_auto_20191122_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
