# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0002_auto_20191118_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='parent_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='parent/'),
            preserve_default=False,
        ),
    ]
