# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('azapp', '0003_auto_20191120_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='partner_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partners',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parents',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
