# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-06 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0003_remove_partners_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=120)),
                ('commented_blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Blog')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Parents')),
            ],
        ),
    ]
