# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0003_auto_20191119_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='activity_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Activities'),
        ),
    ]
