# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0003_auto_20191122_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
