# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0004_child_activity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='activity_name',
            new_name='activity_id',
        ),
    ]
