# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0004_auto_20191120_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='partner_image',
            new_name='partner_name',
        ),
        migrations.AddField(
            model_name='child',
            name='activity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Activities'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='price',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='names',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
