# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0004_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
