# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0004_auto_20191122_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='activity/'),
        ),
    ]
