# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0005_auto_20191121_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='category',
        ),
        migrations.AddField(
            model_name='activities',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Categories'),
        ),
    ]
