# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0005_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azapp.Blog'),
        ),
    ]
