# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
