# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azapp', '0008_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
